### ISSUE TITLE
Disabling _focus styling

### ISSUE THREAD

**Issue by ASalcedoC** [cchanxzy/react-currency-input-field#236]
Is there a way to disable the borderColor change when the component is focused?

**Comment by adjenks** [comment]
@ASalcedoC :

```css
.no-focus-outline:focus {
  outline:none;
}
```
```js
<CurrencyInput className="no-focus-outline"/>
```
